<?php

require "index.php";

class NumberTest extends \PHPUnit\Framework\TestCase
{
    protected function setUp(): void
    {

    }

    protected function tearDown(): void
    {
        //parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testNumber1()
    {
        $this->assertEquals(true,checkNumber('+38066 284-31-47'));
    }

    public function testNumber2()
    {
        $this->assertEquals(true,checkNumber('066 284-31-47'));
    }

    public function testNumber3()
    {
        $this->assertEquals(true,checkNumber('8067-284-31-47'));
    }

    public function testNumber4()
    {
        $this->assertEquals(true,checkNumber('+38066 284 31 47'));
    }

    public function testNumber5()
    {
        $this->assertEquals(true,checkNumber('380662843147'));
    }

    public function testNumber6()
    {
        $this->assertEquals(false,checkNumber('+380662843147s'));
    }

    public function testNumber7()
    {
        $this->assertEquals(false,checkNumber('45354345345354'));
    }

    public function testNumber8()
    {
        $this->assertEquals(false,checkNumber('-+380662843147'));
    }






}